### ISSUE TITLE
Entrypoint.sh fails at first time

### ISSUE THREAD

**Issue by FernandoMorais** [severalnines/docker#15]
Hi all,

I'm getting this error:
```
&gt;&gt; Generating key for s9s cli
One username should be passed as command line argument when creating new user.
```

If I run the container locally without the entrypoint, connect to the container and run the entrypoint.sh manually, it raises the error at first time and work after running again.

The same error is raised when running on a Kubernetes cluster.

There is something I'm missing?

**Comment by FernandoMorais** [comment]
Hi all,

Trying go ahead on running my cluster, I found that the problem occurs only when I attach a volume for `/var/lib/mysql`.

I've tried to clean mais volume dir, but I started to get this error:

```
>> Datadir is empty. Initializing datadir..
[Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
[Note] Ignoring --secure-file-priv value as server is running with --bootstrap.
[Note] /usr/sbin/mysqld (mysqld 5.6.37-82.2) starting as process 28 ...
```

**Comment by FernandoMorais** [comment]
diving some more into this...

I found some inconsistent permissions:

```
[root@... mysql]# ls -la .                       
total 110593
-rwx------ 1 root root      117 Dec 17 03:31 RPM_UPGRADE_HISTORY
-rwx------ 1 root root      117 Dec 17 03:31 RPM_UPGRADE_MARKER-LAST
-rwx------ 1 root root 50331648 Dec 17 03:31 ib_logfile0
-rwx------ 1 root root 50331648 Dec 17 03:31 ib_logfile1
-rwx------ 1 root root 12582912 Dec 17 03:31 ibdata1
drwx------ 2 root root        0 Dec 17 03:31 mysql
drwx------ 2 root root        0 Dec 17 03:31 performance_schema
```

It seams like the `chown -R mysql:mysql "$DATADIR"` line is not working.

**Comment by ralfbecker** [comment]
Have you created the secret for the root password?

-- 
Ralf Becker
EGroupware GmbH

Leibnizstraße 17                                                                                                          67663 Kaiserslautern                                                                                           EMail rb@egroupware.org

Telefon 0631 / 31657-0
Telefax 0631 / 3165726
Mobil    0170 / 7815917

EGroupware:       www.egroupware.org              Outdoor Training: www.outdoor-training.de
digital ROCK:      www.digitalrock.de

Geschäftsführung Ralf und Birgit Becker
Registergericht Kaiserslautern HRB 3587

**Comment by FernandoMorais** [comment]
Hi @ralfbecker!

No, I didn't... I'm following this example: https://github.com/severalnines/docker/tree/master/examples/kubernetes.

**Comment by ashraf-s9s** [comment]
Hi @FernandoMorais 

I've updated the entrypoint script to use the new command to create s9s user. Please delete the existing ClusterControl pod and delete the image on the Kubernetes node so it will download the new image from Docker Hub.

Thanks for reporting this! I'm closing this issue.
