### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by SamEmam** [severalnines/docker#28]
The current Image is at version 1.7.5.3679, while the controller is updated to version 1.7.5.3730.

There are some essential fixes made for the latest update, necessary for us to use your Docker Image.
- General: staging_dir from cmon.cnf is not respected.

https://severalnines.com/docs/changelog.html

Please update to the latest version.

**Comment by ashraf-s9s** [comment]
The image has been updated to 1.8.0. Closing this now.
