### ISSUE TITLE
Cannot Login to V2

### ISSUE THREAD

**Issue by kushalg-1212** [severalnines/docker#37]
I am able to login to V1 but cannot login to v2 

![image](https://github.com/severalnines/docker/assets/111343538/6201b900-4d0d-43d2-bbfe-d3f4b638cd05)

using Cluster Control inside docker with the below Commands 

docker run -d --name clustercontrol \
--network db-cluster \
--ip 192.168.10.10 \
-h clustercontrol \
-p 5000:80 \
-p 5001:443 \
-p 9443:9443 \
-p 19501:19501 \
-e DOCKER_HOST_ADDRESS=192.168.1.103 \
-v /storage/clustercontrol/cmon.d:/etc/cmon.d \
-v /storage/clustercontrol/datadir:/var/lib/mysql \
-v /storage/clustercontrol/sshkey:/root/.ssh \
-v /storage/clustercontrol/cmonlib:/var/lib/cmon \
-v /storage/clustercontrol/backups:/root/backups \
-v /storage/clustercontrol/prom-data:/var/lib/prometheus \
-v /storage/clustercontrol/prom-conf:/etc/prometheus \
severalnines/clustercontrol

**Comment by ashraf-s9s** [comment]
Hi,

Please upgrade to the latest image (tag:latest or tag:1.9.7). The new image does not have this issue anymore.
