### ISSUE TITLE
ClusterControl 1.9.7 is released but not available as docker image

### ISSUE THREAD

**Issue by brgmn** [severalnines/docker#38]
Why is there no docker image for ClusterControl 1.9.7? ClusterControl 1.9.7 has been released end of august but the official docker image hasn't been updated :( Am I missing something? 

https://hub.docker.com/r/severalnines/clustercontrol/tags

**Comment by ashraf-s9s** [comment]
Hi,

We just released the 1.9.7 docker image. It was a major release and a lot of things have changed. There is also a special instruction to upgrade to the 1.9.7 image as shown [here](https://github.com/severalnines/docker/blob/master/UPGRADING-TO-1.9.7.md).
